sudo: required

services:
  - docker

env:
  global:
    - TZ='Europe/Oslo'
    - DATE="$(date +%Y%m%d)"
    - TIME="$(date +%H%M)"
    - COMMIT_NUMBER="$((git fetch --unshallow || true ) && git rev-list --count $TRAVIS_COMMIT)"
    - RELEASE_VERSION="$COMMIT_NUMBER.$DATE.$TIME"
    - APPLICATION_NAME='badkitty'
    - DOCKER_IMAGE_FULL_NAME="navikt/$APPLICATION_NAME:$RELEASE_VERSION"

before_install:
  - echo "Building version $RELEASE_VERSION"
  - docker build -t $APPLICATION_NAME:$RELEASE_VERSION .

#after_deploy:
#  - git remote add auth-origin "https://${GITHUB_ACCESS_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
#  - git tag $RELEASE_VERSION
#  - git push auth-origin --tags
