sudo: required

services:
  - docker

env:
  global:
    - TZ='Europe/Oslo'
    - RELEASE_VERSION="$(if \[ git rev-parse --is-shallow-repository \]; then git fetch --unshallow; else git fetch; fi) && echo $(git rev-list --count $TRAVIS_COMMIT).$(date +\"%Y%m%d\").$(date +\"%H%M\")"
    - APPLICATION_NAME='badkitty'
    - DOCKER_IMAGE_FULL_NAME="navikt/$APPLICATION_NAME:$RELEASE_VERSION"

before_install:
  - docker build -t $APPLICATION_NAME:$VERSION .

#after_deploy:
#  - git remote add auth-origin "https://${GITHUB_ACCESS_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
#  - git tag $RELEASE_VERSION
#  - git push auth-origin --tags
