# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: navikt/badkitty
team: pus
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: badkitty/internal/isAlive
    initialDelay: 20
  readiness:
    path: badkitty/internal/selftest
    initialDelay: 20
